import { GoogleGenAI, Modality } from "@google/genai";

const getApiKey = (): string => {
  const key = process.env.API_KEY;
  if (!key) {
    throw new Error("API_KEY environment variable not set");
  }
  return key;
};

const MODEL_NAME = 'gemini-2.5-flash-image';

const generateImageFromParts = async (parts: any[]): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: { parts },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      const mimeType = part.inlineData.mimeType;
      return `data:${mimeType};base64,${base64ImageBytes}`;
    }
  }

  throw new Error("No image was generated by the model.");
};

export const generateImage = async (logoBase64: string, logoMimeType: string, productDescription: string): Promise<string> => {
  const logoPart = {
    inlineData: {
      data: logoBase64,
      mimeType: logoMimeType,
    },
  };

  const textPart = {
    text: `Place this logo onto a "${productDescription}". The product should be on a clean, neutral background, suitable for a professional product mockup. The logo should be clearly visible and naturally placed.`,
  };

  return generateImageFromParts([logoPart, textPart]);
};

export const editImage = async (imageBase64: string, imageMimeType: string, editPrompt: string): Promise<string> => {
  const imagePart = {
    inlineData: {
      data: imageBase64,
      mimeType: imageMimeType,
    },
  };

  const textPart = {
    text: editPrompt,
  };

  return generateImageFromParts([imagePart, textPart]);
};
